### PR TITLE
[FOR V2] Issue #87

### PR DESCRIPTION
**Pull request by chris-pearce**
https://github.com/chris-pearce/scally/issues/87

### CODE REVIEW

**Comment by chris-pearce** [comment]
@stowball @kllevin can you please review?

**Comment by chris-pearce** [comment]
@stowball @kllevin happy with this?

**Comment by stowball** [comment]
Unless I'm missing something, why would `width: 100%` be set if `$apply-friendly-box-model == false`? Wouldn't that push a input's width past its container because of the internal padding?

**Comment by stowball** [comment]
Also, I'd make your `.ios` class customisable like you do elsewhere:

```
@if $apply-top-inner-shadow-for-ios-inputs { 
  .ios { }
}
```

Because I always use [CssUserAgent](http://cssuseragent.org/) for UA sniffing, which puts on a class of `.ua-ios`

**Comment by chris-pearce** [comment]
@stowball https://github.com/chris-pearce/scally/commit/a54596f4b9442d626cf3be51fb17f962bcfb1b42, some comments here: https://github.com/chris-pearce/scally/blob/%E2%80%9487/core/base/_forms.scss#L54-L56.

For the `.ios` class fix see: https://github.com/chris-pearce/scally/issues/109.

**Pull request merged**
