### PR TITLE
Issue 135: Make the List Object indentation optional and apply `list-style-position: outside` if the indentation is turned off

### PR DESCRIPTION
**Pull request by chris-pearce**
Also made the top and bottom margins configurable.

### CODE REVIEW

**Comment by chris-pearce** [comment]
This fixes #135.

**Comment by chris-pearce** [comment]
@stowball @kllevin could you review please? For V3 I may ditch this entirely and just have lists on by default i.e. use the browser default list styles, or make it a choice?

**Comment by stowball** [comment]
I may be completely wrong, but I think there's some fundamental issues with this file and it's unnecessarily complicated.

I've shaved almost 70 lines off if it below, and I think it's better. There are quite a lot of changes so it's probably best to discuss in person, but give it a whirl and let me know what you think.

``` scss
/* ============================================================================
   @OBJECTS -> LIST
   ========================================================================= */


/**
 * Standard list styles for unordered and ordered lists as they're removed in
 * Core -> Reset.
 *
 * @markup
   <ul class="o-list">
     <li>Lorem</li>
     <li>Aliquam</li>
     <li>Vestibulum</li>
   </ul>

   <ol class="o-list">
     <li>Lorem</li>
     <li>Aliquam</li>
     <li>Vestibulum</li>
   </ol>
 *
 * @demo
 * http://codepen.io/chris-pearce/full/gbVLwy/
 */


/**
 * Settings.
 */

/**
 * Toggle on/off certain styles and treatments.
 true

/**
 * Margins.
 */

$o-list-apply-bottom-margin:                  true !default;

$o-list-apply-top-bottom-margin-to-nested:    false !default;

/**
 * Hanging bullets.
 */

$o-list-apply-hanging-bullets:                true !default;


/**
 * Margins.
 */

$o-list-bottom-margin:                        $spacing-base !default;

$o-list-nested-top-bottom-margin:             $o-list-bottom-margin / 2 !default;

/**
 * Left indentation.
 */

$o-list-indent:                               $o-list-bottom-margin !default;

/**
 * Bullets.
 */

$o-list-bullet-unordered-base:                disc !default;

$o-list-bullet-unordered-nested-once:         circle !default;

$o-list-bullet-unordered-nested-twice:        square !default;

$o-list-bullet-ordered:                       decimal !default;


%o-list,
.o-list {
  @include to-rem(margin-left, $o-list-indent);
  // Apply bottom spacing

  @if $o-list-apply-bottom-margin {
    @include to-rem(margin-bottom, $o-list-bottom-margin);

    // Remove from the last child
    &:last-child {margin-bottom: 0;}
  }

  // Apply hanging bullets
  @if $o-list-apply-hanging-bullets {
    list-style-position: outside;
  }
  @else {
    list-style-position: inside;
  }
}


/**
 * Bullets.
 *
 * For unordered lists we're replicating the native browser bullets:
 * - disc
 *  -- circle
 *    --- square
 */

// Unordered lists
%ul.o-list,
ul.o-list {list-style-type: $o-list-bullet-unordered-base;}

// Ordered lists
%ol.o-list,
ol.o-list {list-style-type: $o-list-bullet-ordered;}


  /**
   * Nested lists.
   */

  %o-list,
  .o-list {

    // Apply spacing between the lists
    @if $o-list-apply-top-bottom-margin-to-nested {
      .o-list {
        @include to-rem(margin-bottom margin-top, $o-list-nested-top-bottom-margin);
      }
    }

    // Unordered list bullets
    ul.o-list {
      list-style-type: $o-list-bullet-unordered-nested-once;

      ul.o-list {list-style-type: $o-list-bullet-unordered-nested-twice;}
    }
  }
```

**Comment by chris-pearce** [comment]
@stowball thanks for taking a look. Yes this one is a bit complex which is why I'm learning towards getting rid of it for V3.

Comments on your edited version:
1. You've removed all the `generate-at-breakpoints()` mixins:
   
   https://github.com/chris-pearce/scally/blob/issue-135/objects/_o-list.scss#L50-L63
   https://github.com/chris-pearce/scally/blob/issue-135/objects/_o-list.scss#L111-L126
   https://github.com/chris-pearce/scally/blob/issue-135/objects/_o-list.scss#L142-L146
   https://github.com/chris-pearce/scally/blob/issue-135/objects/_o-list.scss#L152-L156
   https://github.com/chris-pearce/scally/blob/issue-135/objects/_o-list.scss#L191-L214
   
   Looking at this again I think you only need the one `generate-at-breakpoints()` mixin applied by only one toggle setting: https://github.com/chris-pearce/scally/blob/issue-135/objects/_o-list.scss#L57 as I can't see much need being able to control the list bullets and nested lists and particular breakpoints but I can't change it as it'll be a breaking change. See the compiled CSS snippets below as it might be clearer.
2. This needs to stay: https://github.com/chris-pearce/scally/blob/issue-135/objects/_o-list.scss#L107 otherwise hanging bullets don't work because if you apply a left indentation by default—as per your edited version—and you have `$o-list-apply-hanging-bullets` set to `true` the bullets will be on the inside:
   
   screen shot 2015-05-24 at 7 20 57 am
   
   When it should be:
   
   screen shot 2015-05-24 at 7 21 28 am
3. This: https://github.com/chris-pearce/scally/blob/issue-135/objects/_o-list.scss#L163-L166 can be as your edited version.
4. The reason this section: https://github.com/chris-pearce/scally/blob/issue-135/objects/_o-list.scss#L168-L188 is more verbose than your version is because I've set it up so you only have to apply the selector: `o-list` once to the parent `ol` / `ul` not to every nested `ol` / `ul`.
5. This loop: https://github.com/chris-pearce/scally/blob/issue-135/objects/_o-list.scss#L191 isn't needed so I'll remove.

---

Compiled CSS for the different **apply-at-breakpoints** settings using the **lap** breakpoint:

**CASE 1**

Settings

``` scss
$o-list-apply-at-breakpoints-for-default: true;

$o-list-apply-at-breakpoints-for-unordered: false;

$o-list-apply-at-breakpoints-for-ordered: false;

$o-list-apply-at-breakpoints-for-nested: false;
```

Compiled CSS

``` scss
.o-list {
  margin-bottom: 1.5rem;
  margin-left: 1.5rem;
}
.o-list:last-child {
  margin-bottom: 0;
}

@media (min-width: 40.0625em) {
  .o-list-from-lap {
    margin-bottom: 1.5rem;
    margin-left: 1.5rem;
  }
  .o-list-from-lap:last-child {
    margin-bottom: 0;
  }
}
/**
 * Bullets.
 *
 * For unordered lists we're replicating the native browser bullets:
 * - disc
 *  -- circle
 *    --- square
 */
ul.o-list {
  list-style-type: disc;
}

ol.o-list {
  list-style-type: decimal;
}

/**
 * Nested lists.
 */
.o-list ul,
.o-list ol {
  margin-bottom: 0.75rem;
  margin-top: 0.75rem;
}
.o-list ul,
.o-list ol {
  margin-left: 1.5rem;
}
.o-list ul {
  list-style-type: circle;
}
.o-list ul ul {
  list-style-type: square;
}
.o-list ol {
  list-style-type: decimal;
}
```

**CASE 2**

Settings

``` scss
$o-list-apply-at-breakpoints-for-default: true;

$o-list-apply-at-breakpoints-for-unordered: true;

$o-list-apply-at-breakpoints-for-ordered: false;

$o-list-apply-at-breakpoints-for-nested: false;
```

Compiled CSS

``` scss
.o-list {
  margin-bottom: 1.5rem;
  margin-left: 1.5rem;
}
.o-list:last-child {
  margin-bottom: 0;
}

@media (min-width: 40.0625em) {
  .o-list-from-lap {
    margin-bottom: 1.5rem;
    margin-left: 1.5rem;
  }
  .o-list-from-lap:last-child {
    margin-bottom: 0;
  }
}
/**
 * Bullets.
 *
 * For unordered lists we're replicating the native browser bullets:
 * - disc
 *  -- circle
 *    --- square
 */
ul.o-list {
  list-style-type: disc;
}

@media (min-width: 40.0625em) {
  ul.o-list-from-lap {
    list-style-type: disc;
  }
}
ol.o-list {
  list-style-type: decimal;
}

/**
 * Nested lists.
 */
.o-list ul,
.o-list ol {
  margin-bottom: 0.75rem;
  margin-top: 0.75rem;
}
.o-list ul,
.o-list ol {
  margin-left: 1.5rem;
}
.o-list ul {
  list-style-type: circle;
}
.o-list ul ul {
  list-style-type: square;
}
.o-list ol {
  list-style-type: decimal;
}
```

**CASE 3**

Settings

``` scss
$o-list-apply-at-breakpoints-for-default: true;

$o-list-apply-at-breakpoints-for-unordered: true;

$o-list-apply-at-breakpoints-for-ordered: true;

$o-list-apply-at-breakpoints-for-nested: false;
```

Compiled CSS

``` scss
.o-list {
  margin-bottom: 1.5rem;
  margin-left: 1.5rem;
}
.o-list:last-child {
  margin-bottom: 0;
}

@media (min-width: 40.0625em) {
  .o-list-from-lap {
    margin-bottom: 1.5rem;
    margin-left: 1.5rem;
  }
  .o-list-from-lap:last-child {
    margin-bottom: 0;
  }
}
/**
 * Bullets.
 *
 * For unordered lists we're replicating the native browser bullets:
 * - disc
 *  -- circle
 *    --- square
 */
ul.o-list {
  list-style-type: disc;
}

@media (min-width: 40.0625em) {
  ul.o-list-from-lap {
    list-style-type: disc;
  }
}
ol.o-list {
  list-style-type: decimal;
}

@media (min-width: 40.0625em) {
  ol.o-list-from-lap {
    list-style-type: decimal;
  }
}
/**
 * Nested lists.
 */
.o-list ul,
.o-list ol {
  margin-bottom: 0.75rem;
  margin-top: 0.75rem;
}
.o-list ul,
.o-list ol {
  margin-left: 1.5rem;
}
.o-list ul {
  list-style-type: circle;
}
.o-list ul ul {
  list-style-type: square;
}
.o-list ol {
  list-style-type: decimal;
}
```

**CASE 4**

Settings

``` scss
$o-list-apply-at-breakpoints-for-default: true;

$o-list-apply-at-breakpoints-for-unordered: true;

$o-list-apply-at-breakpoints-for-ordered: true;

$o-list-apply-at-breakpoints-for-nested: true;
```

Compiled CSS

``` scss
.o-list {
  margin-bottom: 1.5rem;
  margin-left: 1.5rem;
}
.o-list:last-child {
  margin-bottom: 0;
}

@media (min-width: 40.0625em) {
  .o-list-from-lap {
    margin-bottom: 1.5rem;
    margin-left: 1.5rem;
  }
  .o-list-from-lap:last-child {
    margin-bottom: 0;
  }
}
/**
 * Bullets.
 *
 * For unordered lists we're replicating the native browser bullets:
 * - disc
 *  -- circle
 *    --- square
 */
ul.o-list {
  list-style-type: disc;
}

@media (min-width: 40.0625em) {
  ul.o-list-from-lap {
    list-style-type: disc;
  }
}
ol.o-list {
  list-style-type: decimal;
}

@media (min-width: 40.0625em) {
  ol.o-list-from-lap {
    list-style-type: decimal;
  }
}
/**
 * Nested lists.
 */
.o-list ul,
.o-list ol {
  margin-bottom: 0.75rem;
  margin-top: 0.75rem;
}
.o-list ul,
.o-list ol {
  margin-left: 1.5rem;
}
.o-list ul {
  list-style-type: circle;
}
.o-list ul ul {
  list-style-type: square;
}
.o-list ol {
  list-style-type: decimal;
}

@media (min-width: 40.0625em) {
  .o-list-from-lap ul,
  .o-list-from-lap ol {
    margin-bottom: 0.75rem;
    margin-top: 0.75rem;
  }
  .o-list-from-lap ul,
  .o-list-from-lap ol {
    margin-left: 1.5rem;
  }
  .o-list-from-lap ul {
    list-style-type: circle;
  }
  .o-list-from-lap ul ul {
    list-style-type: square;
  }
  .o-list-from-lap ol {
    list-style-type: decimal;
  }
}
```

**Pull request merged**
