### PR TITLE
Strip units on passed in values to all functions and mixins

### LINKED ISSUE #80: Strip units on passed in values to em & rem functions and mixins
Currently, the `(to)-em` and `(to)-rem` mixins and functions don't handle anything but unitless values.

I'm so used to passing in a `px` on the end of my string that the output then breaks. It would be great to strip units on whatever was supplied before the calculation.

### PR DESCRIPTION
**Pull request by chris-pearce**
@stowball I pulled down your PR and did a big review and everything was good apart from: 
- I had to apply the `strip-unit` function to [Base -> Root](https://github.com/chris-pearce/scally/blob/master/core/base/_root.scss) (see my commits).
- Same for the [`font-size()`](https://github.com/chris-pearce/scally/blob/master/core/mixins/_font-size.scss) mixin (see my commits). 
- One small thing is the `font-size()` mixin always adds a space before the semi-colon e.g.
  
  ```
  .testing123 {
    font-size: 0.75rem ;
    line-height: inherit ; 
  }
  ```

I also updated some comments (see my commits).

Not ideal to create a brand new PR however it's 11:27pm and my brain has stopped working :)

---

This fixes #80.

### CODE REVIEW

**Comment by chris-pearce** [comment]
Oh I also snook in: https://github.com/chris-pearce/scally/commit/868ff267ae04d38f9c18f7623350471c1ff4bfeb which fixes #122.

**Comment by stowball** [comment]
> had to apply the strip-unit function to Base -> Root (see my commits).. Same for the font-size() mixin (see my commits).

Could catch

> One small thing is the font-size() mixin always adds a space before the semi-colon

Yeah, LibSass doesn't add the space (but doesn't output it), but not having it was what was causing LibSass to error. CSS minification will remove it anyway

**Comment by chris-pearce** [comment]
@stowball @kllevin good to merge?

**Comment by stowball** [comment]
LGTM

**Pull request merged**
