### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by chris-pearce**
**Non-backwards compatible**

@kllevin @chriswrightdesign @stowball I know this is massive but I've tried to keep the commits as concise as possible so probably better to go through each commit rather than reviewing everything. The issues above marked with _TODO_ I still need to do.

### CODE REVIEW

**Comment by chris-pearce** [comment]
@kllevin updates after your code review: https://github.com/chris-pearce/scally/commit/bb4f03c5823fca4a958bc173fcf2d280627c7e0b.

**Comment by chris-pearce** [comment]
#70 done, see commit.

**Comment by chris-pearce** [comment]
#41 done, see commit.

**Comment by chris-pearce** [comment]
#67 done, see commits.

**Comment by chris-pearce** [comment]
Remaining is #65 and #73 which are documentation changes so it's pretty much done from a code POV :+1:

**Comment by chris-pearce** [comment]
@chriswrightdesign @stowball could I get your eyes on this as I'd rather not merge until you've looked at it? I want to merge it before next Mon.

**Comment by chris-pearce** [comment]
@kllevin could you take a look at the last few commits before this gets merged? Thanks.

**Comment by chris-pearce** [comment]
@stowball FYI minor versions do not break backwards compatibility only major:

> > 1. MAJOR version when you make incompatible API changes,
> > 2. MINOR version when you add functionality in a backwards-compatible manner, and
> > 3. PATCH version when you make backwards-compatible bug fixes.

http://semver.org/

**Comment by stowball** [comment]
Ah cool. Good to know

**Comment by kllevin** [comment]
LGTM, other than the small comment on button groups.

**Comment by stowball** [comment]
The style.css file doesn't look like it's up to date. If I do a `sass watch`, the file has a few modifications, Personally, I wouldn't include this generated file in the repo

**Comment by stowball** [comment]
I think we should resolve https://github.com/chris-pearce/scally/issues/68 so that .`.c-button-faux-link` [text-decoration is correctly set](https://github.com/chris-pearce/scally/blob/v2/components/_c-button-faux-link.scss#L26) before v2

**Comment by stowball** [comment]
This is line is incorrectly indented https://github.com/chris-pearce/scally/blob/v2/core/base/_links.scss#L20

**Comment by stowball** [comment]
Did you mean to remove the `display: table` and `display: inherit` utilities in this https://github.com/chris-pearce/scally/commit/3569a05e2f57f1e85dd15b416f4c6f8fa37479a9#diff-f98ee8d4f77940181d5ccfbc218fe1abL83? They might come in handy

**Comment by stowball** [comment]
In _u-spacing.scss, change https://github.com/chris-pearce/scally/blob/v2/utilities/_u-spacing.scss#L1154 to: 

`@each $size, $value in $u-spacing-sizes {` 

so that there's one less thing to update should we add another spacing size such as `mega`

It would be great to make all of the classes dynamic and automatic, but that seems like one hell of a job :cry:

**Comment by stowball** [comment]
Incorrect indentation (tabs & doubled) here https://github.com/chris-pearce/scally/blob/v2/objects/_o-flexible-embed.scss#L139

Actually, there are 14 tabs throughout Scally that need changing.

**Comment by stowball** [comment]
Shouldn't https://github.com/chris-pearce/scally/blob/v2/core/base/_links.scss & https://github.com/chris-pearce/scally/blob/v2/objects/_o-link-complex.scss `$link-color(-hover)` variables be `$color-link(-hover)` to be consistent with other vars?

**Comment by stowball** [comment]
These dark and light overlay modifiers don't look right https://github.com/chris-pearce/scally/blob/v2/objects/_o-overlay.scss#L142. Classes on silent placeholders?

**Comment by stowball** [comment]
Apart from these 8 comments and 2 PRs, v2 looks awesome. Good work @chris-pearce :+1:

**Comment by chris-pearce** [comment]
@stowball thanks for the feedback, some replies:

---

> > The style.css file doesn't look like it's up to date. If I do a sass watch, the file has a few modifications, Personally, I wouldn't include this generated file in the repo

Yeah I'm going to look at removing this from the repo as it's shouldn't be there, it was included to satisfy the `main` property for the package .json files, [Bower's version](https://github.com/bower/bower.json-spec#main). It should be `style.scss`, which I tried when first setting them up but was getting a funny error with Bower. Anyway will revisit.

---

> > I think we should resolve #68 so that ..c-button-faux-link text-decoration is correctly set before v2

I was going to do this as part of the v2 release, both #68 and #97.

---

> > This is line is incorrectly indented https://github.com/chris-pearce/scally/blob/v2/core/base/_links.scss#L20

I think you fixed that in #89? I'll be doing a check of all files and finding a Sublime Text add-on to stop this happening furthermore. 

---

> > Did you mean to remove the display: table and display: inherit utilities in this 3569a05#diff-f98ee8d4f77940181d5ccfbc218fe1abL83? They might come in handy

Yes that was intentional as I'd never used them in all the time they'd been there and it was quite some time. I'm happy to go with what's in the **Display** utility now, let's see how they go and see if they're many requests to add them back. 

---

> > In _u-spacing.scss, change https://github.com/chris-pearce/scally/blob/v2/utilities/_u-spacing.scss#L1154 to:
> > 
> > @each $size, $value in $u-spacing-sizes {
> > 
> > so that there's one less thing to update should we add another spacing size such as mega
> > 
> > It would be great to make all of the classes dynamic and automatic, but that seems like one hell of a job :cry:

Cheers for that and yeah massive job :)

---

> > Incorrect indentation (tabs & doubled) here https://github.com/chris-pearce/scally/blob/v2/objects/_o-flexible-embed.scss#L139
> > 
> > Actually, there are 14 tabs throughout Scally that need changing.

You sorted :+1:. 

---

> > Shouldn't https://github.com/chris-pearce/scally/blob/v2/core/base/_links.scss & https://github.com/chris-pearce/scally/blob/v2/objects/_o-link-complex.scss $link-color(-hover) variables be $color-link(-hover) to be consistent with other vars?

These setting names are correct. All settings start with the thing they're being applied too, in this case it's `link`, here are some settings for [Core -> Base -> Forms](https://github.com/chris-pearce/scally/blob/v2/core/base/_forms.scss#L33-L47). Settings for anything in **Utilities**, **Objects**, and **Components** do the same but also are prefixed with either `u-`, `o-`, and `c-` respectively. But the global settings [here](https://github.com/chris-pearce/scally/tree/v2/core/settings) start with the most common part of what they're applying, so for the colour settings its: `$color-`. All settings should be in context i.e. in the relevant partials, but the global settings can't.

> > These dark and light overlay modifiers don't look right https://github.com/chris-pearce/scally/blob/v2/objects/_o-overlay.scss#L142. Classes on silent placeholders?

I'll look into it, cheers.

**Pull request merged**
