### PR TITLE
Issue 128: Update format for mixins in documentation

### LINKED ISSUE #128: Apply a new format for mixin names when inside comments
Rather than:

> Generate at breakpoints mixin

Let's do:

> `generate-at-breakpoints()` mixin

### PR DESCRIPTION
**Pull request by kllevin**
This fixes #128.

### CODE REVIEW

**Comment by chris-pearce** [comment]
@kllevin thanks for doing this, is this all of the mixins mentioned in the Scally comments? I just thought they'd be more.

**Comment by kllevin** [comment]
I specifically looked at generate-at-breakpoints and generate-at-percentage-breakpoints. I'll do a check for the others.

**Comment by chris-pearce** [comment]
> I specifically looked at generate-at-breakpoints and generate-at-percentage-breakpoints. I'll do a check for the others.

Thanks

**Comment by chris-pearce** [comment]
@kllevin any idea when this will be done? Thanks

**Comment by kllevin** [comment]
@chris-pearce this should be all set.

**Pull request merged**
